### ISSUE TITLE
readFromSSL Missing from JNI native library on osx?

### ISSUE THREAD

**Issue by avboy72** [netty/netty-tcnative#124]
Hello,

I am encountering this error: 
Caused by: java.lang.AbstractMethodError: null
	at org.apache.tomcat.jni.SSL.readFromSSL(Native Method) ~[netty-tcnative-1.1.33.Fork14-osx-x86_64.jar:1.1.33.Fork14]
	at io.netty.handler.ssl.OpenSslEngine.readPlaintextData(OpenSslEngine.java:358) ~[netty-all-4.1.0.CR2.jar:4.1.0.CR2]
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:703) ~[netty-all-4.1.0.CR2.jar:4.1.0.CR2]
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:809) ~[netty-all-4.1.0.CR2.jar:4.1.0.CR2]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1092) ~[netty-all-4.1.0.CR2.jar:4.1.0.CR2]

I am not sure exactly what it means, so any help is appreciated.

**Comment by floragunncom** [comment]
I guess the problem is that OpenSslContext.AbstractCertificateVerifier does not implement

<pre>
int verify(long ssl, byte[][] chain, String auth)
</pre>

but

<pre>
boolean verify(long ssl, byte[][] chain, String auth)
</pre>

**Comment by normanmaurer** [comment]
@avboy72 you need to use netty 4.1.0.CR3.

**Comment by avboy72** [comment]
Oh, sorry...  Is there a compatibility chart somewhere so I can avoid such a snafu in the future?

**Comment by nmittler** [comment]
@normanmaurer this was a breaking change for netty+tcnative ... did we document this anywhere?

**Comment by Scottmitch** [comment]
I'm not sure we have visibly for this yet. Here is one suggestion on how to make this more apparent: https://github.com/netty/netty/issues/4808
