### ISSUE TITLE
 OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.  NEED help

### ISSUE THREAD

**Issue by icesnakejin** [netty/netty-tcnative#140]
I am using fork 16 in my project and got the following error, thanks in advance:

0 [main] INFO com.relayrides.pushy.apns.ApnsClient  - OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:285)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:261)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:742)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:395)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:392)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:386)
	at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:363)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:264)
	at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:238)
	at com.....service.Sender.SendAPNS(Sender.java:270)
	at com.....sender.SenderApp.run(SenderApp.java:152)
	at com.....sender.SenderApp.main(SenderApp.java:98)
Caused by: java.lang.RuntimeException: ALPN unsupported. Is your classpatch configured correctly? See http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-starting
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$1.<init>(JdkAlpnApplicationProtocolNegotiator.java:27)
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator.<clinit>(JdkAlpnApplicationProtocolNegotiator.java:24)
	... 12 more

**Comment by trustin** [comment]
Any DEBUG level log messages? Did you enable DEBUG level logging for Netty?

**Comment by normanmaurer** [comment]
Was a classpath issue as stated on on the google group
