### ISSUE TITLE
netty instance crashed when OpenSslEngine.unwrap

### ISSUE THREAD

**Issue by jingene** [netty/netty-tcnative#176]
Hi. I upgraded netty version recently, instance crashed sometimes.

netty : 4.0.37.Final
tcnative : 1.1.33.Fork17-linux-x86_64
OS : CentOS 6.5

below are core dump.
```
Stack: [0x00007fc416a68000,0x00007fc416b69000],  sp=0x00007fc416b66bc0,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libcrypto.so.10+0x758e9]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 7541  org.apache.tomcat.jni.SSL.readFromSSL(JJI)I (0 bytes) @ 0x00007fc47a42b947 [0x00007fc47a42b900+0x47]
J 17879 C2 io.netty.handler.ssl.OpenSslEngine.unwrap([Ljava/nio/ByteBuffer;II[Ljava/nio/ByteBuffer;II)Ljavax/net/ssl/SSLEngineResult; (821 bytes) @ 0x00007fc47b3c3120 [0x00007fc47b3c2c00+0x520]
J 17365 C2 io.netty.handler.ssl.SslHandler.unwrap(Ljavax/net/ssl/SSLEngine;Lio/netty/buffer/ByteBuf;IILio/netty/buffer/ByteBuf;)Ljavax/net/ssl/SSLEngineResult; (149 bytes) @ 0x00007fc47bc32e34 [0x00007fc47bc31020+0x1e14]
J 13741 C2 io.netty.handler.ssl.SslHandler.unwrap(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;II)Z (452 bytes) @ 0x00007fc47b357664 [0x00007fc47b357500+0x164]
J 13308 C2 io.netty.handler.ssl.SslHandler.decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V (275 bytes) @ 0x00007fc47a921e58 [0x00007fc47a921920+0x538]
J 13538 C2 io.netty.handler.codec.ByteToMessageDecoder.callDecode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V (172 bytes) @ 0x00007fc479fa370c [0x00007fc479fa3520+0x1ec]
J 15567 C2 io.netty.handler.codec.ByteToMessageDecoder.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (317 bytes) @ 0x00007fc47b830710 [0x00007fc47b830220+0x4f0]
J 11072 C2 io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(Lio/netty/channel/ChannelHandlerContext;)V (70 bytes) @ 0x00007fc4797c23f4 [0x00007fc4797c2220+0x1d4]
J 17376 C2 io.netty.handler.codec.ByteToMessageDecoder.callDecode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V (172 bytes) @ 0x00007fc479fa370c [0x00007fc479fa3520+0x1ec]
J 15567 C2 io.netty.handler.codec.ByteToMessageDecoder.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (317 bytes) @ 0x00007fc47b830710 [0x00007fc47b830220+0x4f0]
J 9792 C2 io.netty.channel.ChannelInboundHandlerAdapter.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (9 bytes) @ 0x00007fc479f7abb0 [0x00007fc479f7aa60+0x150]
J 9583 C2 io.netty.handler.timeout.IdleStateHandler.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (42 bytes) @ 0x00007fc47a9f02dc [0x00007fc47a9f0160+0x17c]
J 9737 C2 io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V (9 bytes) @ 0x00007fc47a43e3f0 [0x00007fc47a43e2a0+0x150]
```
Thanks in advance.

**Comment by normanmaurer** [comment]
@jingene can you please upgrade to 4.0.40.Final with latest tcnative and let me know if you still see it ?

**Comment by jingene** [comment]
@normanmaurer OK. I'll try it. :)

**Comment by jingene** [comment]
@normanmaurer I updated netty and tcnative, ssl negotiation error occurred.
version 
  - netty : 4.0.40.Final
  - tcnative : 1.1.33.Fork19

below are errors.
2016-08-08 11:00:33|WARN |nioEventLoopGroup-3-1|[id: 0x4981bae4, L:/182.162.201.207:443 - R:/10.33.69.58:53013] TLS handshake failed:
javax.net.ssl.SSLHandshakeException: error:00000000:lib(0):func(0):reason(0)
        at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:620)
        at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:607)
        at io.netty.handler.ssl.OpenSslEngine.handshake(OpenSslEngine.java:1286)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:691)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:855)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:898)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
2016-08-08 11:00:33|WARN |nioEventLoopGroup-3-1|An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:00000000:lib(0):func(0):reason(0)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:219)
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:616)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:457)
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:417)
Caused by: javax.net.ssl.SSLHandshakeException: error:00000000:lib(0):func(0):reason(0)
        at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:620)
        at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:607)
        at io.netty.handler.ssl.OpenSslEngine.handshake(OpenSslEngine.java:1286)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:691)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:855)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:898)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode

**Comment by normanmaurer** [comment]
@jingene is it easy to reproduce for me ?

**Comment by Scottmitch** [comment]
+1. reproducer would make it much easier to debug :)

Can you explain what is happening in terms of packets being exchanged during the handshake process? At what point is the handshake failing, who initiates the failure, is this a re-negotiation or initial handshake, are you using session tickets or TLS extensions (ALPN), etc...

What is `sslError` at `OpenSslEngine.handshake(OpenSslEngine.java:1286)` when this occurs?

**Comment by jingene** [comment]
@normanmaurer @Scottmitch 
I'm sorry for late response. I updated openssl version(openssl-e -> openssl-t) and crash was disappeared until now. I'll attach reproduce step when crash occurred again. Thanks!

**Comment by normanmaurer** [comment]
@jingene but what about the handshake error ?
