### ISSUE TITLE
1.1.33.Fork23 fails on Mac OS X 10.9.5 (Mavericks) using OpenSSL mode

### ISSUE THREAD

**Issue by jprante** [netty/netty-tcnative#197]
When using artifact `io.netty:netty-tcnative:1.1.33.Fork23:osx-x86_64` from Maven Central, the loading of the native library fails on Mac OS X 10.9.5 (Mavericks) with the exception given below.

1.1.33.Fork19 does work on Mac OS X 10.9.5 (Mavericks).

Suggestion: the wiki http://netty.io/wiki/forked-tomcat-native.html should contain a note about what released artifacts support what OS releases, or which libapr-1 version was used, respectively.

```
[15:39:36,788][DEBUG][io.netty.util.internal.NativeLibraryLoader][Test worker] Unable to load the library: netty-tcnative.
java.lang.UnsatisfiedLinkError: /private/var/folders/v5/vvl6jhqs0cz_krl674_yb6980000gn/T/libnetty-tcnative8917743387072026946.dylib: dlopen(/private/var/folders/v5/vvl6jhqs0cz_krl674_yb6980000gn/T/libnetty-tcnative8917743387072026946.dylib, 1): Library not loaded: /usr/local/opt/apr/libexec/lib/libapr-1.0.dylib
  Referenced from: /private/var/folders/v5/vvl6jhqs0cz_krl674_yb6980000gn/T/libnetty-tcnative8917743387072026946.dylib
  Reason: Incompatible library version: libnetty-tcnative8917743387072026946.dylib requires version 6.0.0 or later, but libapr-1.0.dylib provides version 5.0.0
    at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_92]
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_92]
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_92]
    at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_92]
    at java.lang.System.load(System.java:1086) ~[?:1.8.0_92]
    at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:214) ~[netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:161) [netty-common-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:325) [netty-handler-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:90) [netty-handler-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:169) [netty-handler-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:347) [netty-handler-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:337) [netty-handler-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:413) [netty-handler-4.1.4.Final.jar:4.1.4.Final]
    at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:391) [netty-handler-4.1.4.Final.jar:4.1.4.Final]

```

**Comment by Scottmitch** [comment]
agreed our docs could use some improvement in this area. However the exception indicates an issue with the apr library ... does updating this library solve your issue?

**Comment by jprante** [comment]
There is no known method to me how to update `/usr/lib/libapr-1.0.dylib` on Mac OS X Mavericks without breaking the system. I assume the error will disappear using macOS Sierra.

**Comment by Scottmitch** [comment]
IIUC the latest artifact was built on macOS Sierra with a apr obtained from `brew` ... ( @normanmaurer - correct me if I'm wrong)

**Comment by Scottmitch** [comment]
@jprante - Have you tried building your own APR?

**Comment by jprante** [comment]
Installing APR 1.5.2 by `brew install apr` works.

```
$ otool  -L /usr/lib/libapr-1.dylib 
/usr/lib/libapr-1.dylib:
	/usr/lib/libapr-1.0.dylib (compatibility version 5.0.0, current version 5.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

$ otool -L /usr/local/Cellar/apr/1.5.2/libexec/lib/libapr-1.0.dylib 
/usr/local/Cellar/apr/1.5.2/libexec/lib/libapr-1.0.dylib:
	/usr/local/opt/apr/libexec/lib/libapr-1.0.dylib (compatibility version 6.0.0, current version 6.2.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

I'm not sure how netty-tcnative prefers `/usr/local/opt/apr/libexec/lib/libapr-1.0.dylib` but it seems to work somehow. Anyway, documentation would be much welcome.

**Comment by normanmaurer** [comment]
Yes you need to install apr via brew as sierra not ships it anymore. I will update the docs soon

**Comment by normanmaurer** [comment]
Updated details here:

https://github.com/netty/netty/wiki/Forked-Tomcat-Native
