### ISSUE TITLE
Static and Dynamic libraries working on macOS but not on Ubuntu and Fedora

### ISSUE THREAD

**Issue by AshleyByeUK** [netty/netty-tcnative#292]
I've an app which runs absolutely fine with both the dynamically and statically linked libraries on macOS using `1.1.33.Fork26` against `OpenSSL 1.0.21` and `APR 1.6.2` (both through homebrew). However, on both Ubuntu 17.04 and and Fedora 25 I get the following exception (it looks like a Vert.x exception which obfuscates the original, so probably not much help to you guys):
```
Jun 30, 2017 11:56:17 PM io.vertx.core.impl.DeploymentManager
SEVERE: ALPN not available for JDK SSL/TLS engine
io.vertx.core.VertxException: ALPN not available for JDK SSL/TLS engine
	at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:89)
	at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:169)
	at io.vertx.grpc.VertxServer$ActualServer.<init>(VertxServer.java:52)
	at io.vertx.grpc.VertxServer$ActualServer.<init>(VertxServer.java:37)
	at io.vertx.grpc.VertxServer.lambda$start$1(VertxServer.java:126)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.vertx.grpc.VertxServer.start(VertxServer.java:126)
	at uk.ashleybye.grpc.tls.Server.start(Server.kt:36)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

Jun 30, 2017 11:56:17 PM io.vertx.core.impl.DeploymentManager
SEVERE: ALPN not available for JDK SSL/TLS engine
io.vertx.core.VertxException: ALPN not available for JDK SSL/TLS engine
	at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:89)
	at io.vertx.core.net.impl.SSLHelper.<init>(SSLHelper.java:150)
	at io.vertx.grpc.VertxChannelBuilder.build(VertxChannelBuilder.java:148)
	at uk.ashleybye.grpc.tls.Client.start(Client.kt:22)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```
On both Ubuntu and Fedora, neither the static nor dynamic libraries work - I've tried most of the releases from `1.1.33.Fork7` onwards and all of the 2.0x releases, both dynamic and static. On Fedora, I have `OpenSSL 1.0.2k-fips` and `APR 1.5.2`. Ubuntu is `OpenSSL 1.0.2g` and `APR 1.5.2-5`.

I find it odd that this works on macOS but not on any of the other OS's I have tried it on. It's obviously entirely possible that I've misconfigured something, but to have done that twice when my dependencies meet the minimum (according to [grpc-java](https://github.com/grpc/grpc-java/blob/master/SECURITY.md) anyway) and it is working elsewhere makes me wonder if there is some issue with the library packages. That said, for none of them to work makes me think that it could well be a configuration issue.

Is this something you're able to provide any clarity on and perhaps some suggestions as to system configuration steps that I may have missed?

**Comment by Scottmitch** [comment]
From a Netty perspective http://netty.io/wiki/forked-tomcat-native.html should provide enough information for you to use netty-tcnative (and even compile it your self). Have you tried using the most recently released versions of Netty and netty-tcnative? Can you provide a minimal Netty-only reproducer for your issue and describe any additional relevant configuration on the host machines?

**Comment by normanmaurer** [comment]
Let me close this as there was no followup with more infos.
