### ISSUE TITLE
AUFS docker filesystem not working

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#311]
* netty 4.1.13 
* on dockerized ubuntu 14.04 with openssl 1.1.0f and libapr1 1.5.2
* OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
* netty-tcnative-2.0.5.Final-linux-x86_64.jar

When /tmp is mounted on AUFS like 

`none on / type aufs (rw,relatime,si=357364fc583ca134,dio,dirperm1)`

it results in

<pre>
[2017-10-19T11:00:05,733][DEBUG][i.n.u.i.NativeLibraryLoader] -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
[2017-10-19T11:00:05,737][DEBUG][i.n.u.i.NativeLibraryLoader] -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)

java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-linux-x86_64, netty-tcnative-linux-x86_64-fedora, netty-tcnative, netty_tcnative]

[2017-10-19T11:00:05,760][DEBUG][i.n.u.i.NativeLibraryLoader] Unable to load the library '/tmp/libnetty-tcnative8142841543467298681.so', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative8142841543467298681.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_141]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_141]
	at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_141]
	at java.lang.System.load(System.java:1086) ~[?:1.8.0_141]
</pre>

**Comment by normanmaurer** [comment]
I think this was "fixed" in netty by logging a warning and tell people to use a different directory:

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L191
