### ISSUE TITLE
java.lang.UnsatisfiedLinkError: io.netty.internal.tcnative.Library.aprMajorVersion()I

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#312]
* netty 4.1.13
* on ubuntu 14.04 with openssl 1.1.0f and libapr1 1.5.2
* OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
* netty-tcnative-2.0.5.Final-linux-x86_64.jar

APR was installed with `sudo apt-get -y update && sudo apt-get -y install libapr1`

<pre>
[2017-10-19T13:52:24,549][DEBUG][i.n.u.i.NativeLibraryLoader] Successfully loaded the library: netty-tcnative-linux-x86_64
[2017-10-19T13:52:24,552][DEBUG][i.n.h.s.OpenSsl          ] Failed to initialize netty-tcnative; OpenSslEngine will be unavailable. See http://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.UnsatisfiedLinkError: io.netty.internal.tcnative.Library.aprMajorVersion()I
	at io.netty.internal.tcnative.Library.aprMajorVersion(Native Method) ~[netty-tcnative-2.0.5.Final-linux-x86_64.jar:2.0.5.Final]
	at io.netty.internal.tcnative.Library.initialize(Library.java:128) ~[netty-tcnative-2.0.5.Final-linux-x86_64.jar:2.0.5.Final]
	at io.netty.internal.tcnative.Library.initialize(Library.java:113) ~[netty-tcnative-2.0.5.Final-linux-x86_64.jar:2.0.5.Final]
</pre>

**Comment by Scottmitch** [comment]
We don't yet support 1.1.x. Related:

https://github.com/netty/netty-tcnative/pull/249
https://github.com/netty/netty/issues/6320

**Comment by normanmaurer** [comment]
Please check https://github.com/netty/netty/issues/6320#issuecomment-338983404

**Comment by dfeng99** [comment]
Hi,

I have the same issue. It seems that aprMajorVersion() evaluation failed in Library.java at line 149.

My environment:
netty 4.1.19
on ubuntu 16.04 with openssl 1.0.2g and libapr1 1.5.2-3
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
netty-tcnative-2.0.7.Final-linux-x86_64

**Comment by dfeng99** [comment]
Oh, I found I had an old libnetty-tcnative 1.1.33 which installed by apt-get, after remove, it works.

**Comment by normanmaurer** [comment]
Our static openssl build uses 1.1.1 now. Closing
