### ISSUE TITLE
NoClassDefFoundError when building tcnative on Ubuntu

### ISSUE THREAD

**Issue by doom369** [netty/netty-tcnative#36]
Hi,

I was following instructions from wiki

```
sudo apt-get install autoconf automake libtool make tar libapr1-dev libssl-dev
git clone https://github.com/netty/netty-tcnative.git
cd netty-tcnative
git checkout netty-tcnative-1.1.32.Fork1
mvn clean install
```
And getting :
```
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: linux-x86_64


Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/RepositorySystemSession
	at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:115)
	at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:92)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.RepositorySystemSession
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 15 more

```

**Comment by normanmaurer** [comment]
@doom369 you need to use maven 3.2.1 or higher.

**Comment by normanmaurer** [comment]
@doom369 sorry correct.. 3.1.1 or higher.

**Comment by doom369** [comment]
Ok, thanks, it works with latest. Maybe this should be added to wiki.

**Comment by normanmaurer** [comment]
@doom369 yep.. Also will add some enforcer rules so it is easier to understand what is wrong.

**Comment by normanmaurer** [comment]
Added some enforcer rule to catch this...

**Comment by doom369** [comment]
Cool, thanks!
