### ISSUE TITLE
 Failed to load any of the given libraries: [netty_tcnative_linux_aarch_64]

### ISSUE THREAD

**Issue by liuhea** [netty/netty-tcnative#371]
```
sslCtx = SslContextBuilder
                    .forClient()
                    .sslProvider(SslProvider.OPENSSL)
                    .trustManager(SingUtilsKt.openAsset(this, "ca.cer"))
                    .keyManager(SingUtilsKt.openAsset(this, "cc.crt"), SingUtilsKt.openAsset(this, "cc.pkcs8.pem"))
                    .clientAuth(ClientAuth.REQUIRE).build();
```
### Expected behavior
     Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_aarch_64, netty_tcnative_linux_aarch_64_fedora, netty_tcnative]

### Netty version
    implementation group: 'io.netty', name: 'netty-handler', version: '4.1.15.Final'
    implementation group: 'io.netty', name: 'netty-tcnative-boringssl-static', version: '2.0.6.Final'

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

### OS version (e.g. `uname -a`)
Linux liuhe-linux 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by liuhea** [comment]
link https://github.com/netty/netty/issues/8101

**Comment by Ravipatel401** [comment]
**I have tried google cloud speech API integration but working my PC, and tried to integrate in server pc and another laptop showing same error.**

INFO: netty-tcnative unavailable (this may be normal)
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_32, netty_tcnative_x86_32, netty_tcnative]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:440)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:97)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:244)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:171)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:120)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:385)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:414)
	at 


**Please Give me Detail solution.
Version Details :
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)**

Thanks

**Comment by normanmaurer** [comment]
Use a 64 bit JVM
