### ISSUE TITLE
TCN 2.0.12: error:00000000:lib(0):func(0):reason(0)

### ISSUE THREAD

**Issue by rkapsi** [netty/netty-tcnative#373]
... in conjunction with Netty 4.1.27

We're observing a small drop in successful TLS handshakes and a proportional increase in failed handshakes when upgrading from previous TCN/Netty to current version. At the same time the OpenSSL `error:00000000:lib(0):func(0):reason(0)` error makes an appearance and seems to match the drop.

Digging a bit on the Internet (e.g. [1](https://github.com/openssl/openssl/issues/1272), [2](http://openssl.6102.n7.nabble.com/SSL-negotiation-failed-error-00000000-lib-0-func-0-reason-0-td49570.html)) seems to indicate that it's emitted by `ERR_error_string(...)` when a 0 error code is being passed in, which `ERR_get_error()` may return.

Wonder if OpenSSL 1.1.0 is just better at detecting some error or if TCN is erroneously raising an error that isn't one?

**Comment by rkapsi** [comment]
@normanmaurer 

```java
2018-07-17 21:19:19,627 11478 [HttpsWorkerThread-8] HttpOrHttp2 ERROR: channel=[id: 0xe14f61ab, L:/xxx.xxx.xxx.xxx:443 - R:/yyy.yyy.yyy.yyy:60575]
 javax.net.ssl.SSLHandshakeException: error:00000000:lib(0):func(0):reason(0)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:871) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1120) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1075) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1142) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1185) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at com.squarespace.echo.core.metrics.TrafficMetrics.channelRead(TrafficMetrics.java:61) [echo-core-2.34-20180717-rkapsi_netty-tcnative-2.0.12-take2-5.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.27.Final.jar:4.1.27.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by rkapsi** [comment]
@normanmaurer my original assessment regards increased handshake errors was due to DHE (but I didn't know that yet). With that fixed there seems to be a 1 to 1 shift from one set of errors to a different set of errors. When I do a `sumSeries(...)` over the graph below it looks exactly the same between 1.0.2 and 1.1.0.

![screenshot from 2018-08-29 11-03-23](https://user-images.githubusercontent.com/191635/44797196-9641f700-ab7c-11e8-884a-7e3b4a547346.png)

**Comment by normanmaurer** [comment]
Ok that’s good... do still see the same kind of errors as reported here tho ?

**Comment by rkapsi** [comment]
Yea, still present. It's the purple line on the right hand side of the graph (the most frequent error). It seems to have been `error_140940e5_ssl_routines_ssl3_read_bytes_ssl_handshake_failure` (baby blue) under 1.0.2.

**Comment by rkapsi** [comment]
(pay no attention to the harmonicity of the errors; it's some pesky/badly written bot that keeps coming back every couple of minutes)

**Comment by normanmaurer** [comment]
And this has the „error:00000000:lib(0):func(0):reason(0)“ ?

**Comment by normanmaurer** [comment]
Would be interesting to see the log after this is applied https://github.com/netty/netty/pull/8236

**Comment by rkapsi** [comment]
Correct.

The names in the legend of the graph are simply normalized versions of the OpenSSL error strings (all `:()` replaced with `_` just so that the time series db doesn't get a hiccup)

**Comment by rkapsi** [comment]
Shouldn't be a problem to get netty/netty#8236 deployed on our end.
