### ISSUE TITLE
Why is 64 bit windows trying to load 32 bit libraries?

### ISSUE THREAD

**Issue by theangrydev** [netty/netty-tcnative#374]
Windows 10 64 bit
Java 8 Update 144

For some reason I see the following:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:336)
at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:202)
at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:43)
at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:347)
at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:335)
at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:421)
at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:441)
at ...
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_32, netty_tcnative_x86_32, netty_tcnative]
```

Why is it attempting to load the 32 bit libraries?

**Comment by theangrydev** [comment]
For the record, this happened because of running the 32bit JVM on a 64bit OS
