### ISSUE TITLE
Issue with latest 2.0.21.Final openssl dynamic

### ISSUE THREAD

**Issue by fzakaria** [netty/netty-tcnative#439]
Hey @normanmaurer 

I'm testing out the new 2.0.21.Final openssl dynamic to update https://github.com/netty/netty/pull/8699 however I'm running into some _UnsatisfiedLinkError_ namely when it tries to do `OpenSsl#initializeTcNative`

```
09:51:52.094 [main] DEBUG i.n.u.internal.NativeLibraryLoader - [netty_tcnative, /var/folders/s6/71m49dmx1_s40dm2jkt42pw80000gn/T, java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path] cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: [netty_tcnative, /var/folders/s6/71m49dmx1_s40dm2jkt42pw80000gn/T, java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path]
09:51:52.128 [main] DEBUG i.n.u.internal.NativeLibraryLoader - Successfully loaded the library /var/folders/s6/71m49dmx1_s40dm2jkt42pw80000gn/T/libnetty_tcnative7133977999480943680.dylib
09:51:52.128 [main] DEBUG io.netty.handler.ssl.OpenSsl - Initialize netty-tcnative using engine: 'default'
09:51:52.133 [main] DEBUG io.netty.handler.ssl.OpenSsl - Failed to initialize netty-tcnative; OpenSslEngine will be unavailable. See http://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.UnsatisfiedLinkError: io.netty.internal.tcnative.Library.aprMajorVersion()I
	at io.netty.internal.tcnative.Library.aprMajorVersion(Native Method)
	at io.netty.internal.tcnative.Library.initialize(Library.java:149)
	at io.netty.handler.ssl.OpenSsl.initializeTcNative(OpenSsl.java:531)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:110)
	at io.netty.handler.ssl.OpenSslEngineTest.data(OpenSslEngineTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.runners.Parameterized.allParameters(Parameterized.java:280)
	at org.junit.runners.Parameterized.<init>(Parameterized.java:248)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.junit4.JUnit4TestRunnerUtil.getParameterizedRequest(JUnit4TestRunnerUtil.java:252)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:172)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:46)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
If I revert it back to the SNAPSHOT I was using from when my pull-request to netty-tcnative was accepted, it continues to work.

**Comment by normanmaurer** [comment]
@fzakaria thats strange... what OS you are on ? Also are you sure there is not another version on the class path ?

**Comment by fzakaria** [comment]
Hmm -- I'm still debugging but stepping through it seems to be finding the correct JAR & dylib
`jar:file:/Users/fmzakari/.m2/repository/io/netty/netty-tcnative/2.0.21.Final/netty-tcnative-2.0.21.Final-osx-x86_64.jar!/META-INF/native/libnetty_tcnative.jnilib`

**Comment by normanmaurer** [comment]
@fzakaria yeah seems like there is something wrong... let me check.

**Comment by normanmaurer** [comment]
@fzakaria can you please try 2.0.22.Final ?

**Comment by fzakaria** [comment]
Looks good.
What was the problem ?

**Comment by normanmaurer** [comment]
I did somehow mess up the build when doing the release 🤷‍♂️
