### ISSUE TITLE
Cannot run a file that does not have a valid format while running: CertificateVerifierTest

### ISSUE THREAD

**Issue by amandeepgautam** [netty/netty-tcnative#441]
I am trying to compile netty-tcnative on AIX. There have been a few issues but I am past all of them and can succesfully generate the artefact `/tmp/apace-maven/apache-maven-3.6.0/bin/mvn install -Dmaven.test.skip=true`.  However, when I run it as: `/tmp/apace-maven/apache-maven-3.6.0/bin/mvn -X install`, the following error is generated.

```
Running io.netty.internal.tcnative.CertificateVerifierTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.102 sec <<< FAILURE! - in io.netty.internal.tcnative.CertificateVerifierTest
io.netty.internal.tcnative.CertificateVerifierTest  Time elapsed: 0.102 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: /home/amandeep/netty-tcnative/openssl-dynamic/target/test-classes/META-INF/native/aix64/libnetty_tcnative.a (   0509-022 Cannot load module /home/amandeep/netty-tcnative/openssl-dynamic/target/test-classes/META-INF/native/aix64/libnetty_tcnative.a.
        0509-026 System error: Cannot run a file that does not have a valid format.)
        at java.lang.ClassLoader.loadLibraryWithPath(ClassLoader.java:1276)
        at java.lang.System.load(System.java:535)
        at io.netty.internal.tcnative.AbstractNativeTest.loadNativeLib(AbstractNativeTest.java:40)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:495)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

```

Any idea on how to solve this?

**Comment by normanmaurer** [comment]
Sorry no... I have no AIX system to investigate on.

**Comment by normanmaurer** [comment]
As told before AIX is not supported atm. So closing this
