### ISSUE TITLE
java.lang.UnsatisfiedLinkError: io/netty/internal/tcnative/Library.aprMajorVersion()I  

### ISSUE THREAD

**Issue by amandeepgautam** [netty/netty-tcnative#443]
I am trying to build netty-tcnative for AIX and am facing errors. I was able to resovle https://github.com/netty/netty-tcnative/issues/441 and https://github.com/netty/netty-tcnative/issues/436 but cannot figure out the following error. It would be great if someone could explain what it means.

```
Running io.netty.internal.tcnative.CertificateVerifierTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.085 sec <<< FAILURE! - in io.netty.internal.tcnative.CertificateVerifierTest
io.netty.internal.tcnative.CertificateVerifierTest  Time elapsed: 0.085 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: io/netty/internal/tcnative/Library.aprMajorVersion()I
        at io.netty.internal.tcnative.Library.initialize(Library.java:149)
        at io.netty.internal.tcnative.Library.initialize(Library.java:134)
        at io.netty.internal.tcnative.AbstractNativeTest.loadNativeLib(AbstractNativeTest.java:41)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:495)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

Follwoing is my environment:
-- builiding tcnative from source.
-- AIX 7.2
-- JVM: IBM J9 VM (build 2.8, JRE 1.8.0 AIX ppc64-64 Compressed References 20150116_231420 (JIT enabled, AOT enabled)

Let me know if any other information is needed.

**Comment by amandeepgautam** [comment]
@normanmaurer could you please look.

**Comment by johnou** [comment]
@amandeepgautam I think the stacktrace you pasted is truncated, would you please paste the entire thing.

**Comment by zergweak** [comment]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.053 sec <<< FAILURE! - in io.netty.internal.tcnative.CertificateVerifierTest
io.netty.internal.tcnative.CertificateVerifierTest  Time elapsed: 0.053 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: io.netty.internal.tcnative.Library.aprMajorVersion()I
	at io.netty.internal.tcnative.Library.aprMajorVersion(Native Method)
	at io.netty.internal.tcnative.Library.initialize(Library.java:149)
	at io.netty.internal.tcnative.Library.initialize(Library.java:134)
	at io.netty.internal.tcnative.AbstractNativeTest.loadNativeLib(AbstractNativeTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


I  get same error. 
but i usd jdk 1.7
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode).

When I used jdk1.8 it was all right.

**Comment by normanmaurer** [comment]
@zergweak so it only happens on Java7 but the same works with java8 correct ?

**Comment by zergweak** [comment]
@normanmaurer yes, used Java 8 is ok.

**Comment by normanmaurer** [comment]
@zergweak will check... that said I think we generally not support JDK7 with the native implementation in netty.

**Comment by zergweak** [comment]
@normanmaurer Thank you very much.

**Comment by normanmaurer** [comment]
Let me close this as we not support java7 in netty-tcnative.
