### ISSUE TITLE
java.lang.IllegalArgumentException: TLSv1.3java.lang.IllegalArgumentException: TLSv1.3

### ISSUE THREAD

**Issue by User979269852** [netty/netty-tcnative#462]
when I update netty-tcnative-boringssl-static's version from 2.0.14.Final to 2.0.20.Final.something bad happened:Caused by: java.lang.IllegalArgumentException: TLSv1.3
        at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:187)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:258)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
        at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:237)
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:621)

Can anyone give me some tips?Thanks a lot

**Comment by normanmaurer** [comment]
Please update to latest netty version + netty-tcnative version or use java8.

**Comment by ross-t** [comment]
I'm experiencing this with Netty v4.1.35.Final (via Play) and netty-tcnative-boringssl-static v2.0.20.Final on openjdk 8.

If I'm traversing backwards through Netty changeblogs correctly, [4.1.32.Final](https://netty.io/news/2018/11/29/4-1-32-Final.html) is the most recent pre-4.1.35.Final release calling for a tcnative version bump, so 2.0.20.Final _should_ be the right version. I tried on 2.0.26.Final just in case and experienced the same problem.

As an aside, if you've got open docs, I'd love to add a compatibility table or something to make it easier to figure out which netty-tcnative-boringssl-static version is compatible with a given Netty version.

**Comment by xiezhaokun** [comment]
I found that openjdk8u262 and below will throw this exception.
