### ISSUE TITLE
Possible memory leak in ssl.c

### ISSUE THREAD

**Issue by creamsoup** [netty/netty-tcnative#532]
After PR #498, AddressSanitizer test starts to fail.

```
ERROR: LeakSanitizer: detected memory leaks

Too many leaks! Only the first 5000 leaks encountered will be reported.
Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x56273d7f14dd in malloc llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x56274231e008 in OPENSSL_malloc boringssl/src/crypto/mem.c:112:15
    #2 0x56273e99d081 in new_ssl_state netty_tcnative/openssl-dynamic/src/main/c/ssl.c:905:30
    #3 0x56273e99d081 in netty_internal_tcnative_SSL_newSSL netty_tcnative/openssl-dynamic/src/main/c/ssl.c:951:18
    #4 0x7f62f3967282  (<unknown module>)
    #5 0x7f62f3955bcf  (<unknown module>)
    #6 0x7f62f39560f5  (<unknown module>)
    #7 0x7f62f39560f5  (<unknown module>)
    #8 0x7f62f3955e3f  (<unknown module>)
    #9 0x7f62f3955e3f  (<unknown module>)
    #10 0x7f62f3955e3f  (<unknown module>)
    #11 0x7f62f395613a  (<unknown module>)
    #12 0x7f62f39560f5  (<unknown module>)
    #13 0x7f62f39560f5  (<unknown module>)
    #14 0x7f62f3955e3f  (<unknown module>)
    #15 0x7f62f3955f26  (<unknown module>)
    #16 0x7f62f39560f5  (<unknown module>)
    #17 0x7f62f39560f5  (<unknown module>)
    #18 0x7f62f395613a  (<unknown module>)
    #19 0x7f62f39560f5  (<unknown module>)
    #20 0x7f62f39560f5  (<unknown module>)
```

**Comment by normanmaurer** [comment]
Interesting... will have a look

**Comment by normanmaurer** [comment]
@creamsoup PTAL https://github.com/netty/netty-tcnative/pull/533
