### ISSUE TITLE
Failed to initialize a channel on aarch64

### ISSUE THREAD

**Issue by odidev** [netty/netty-tcnative#577]
I am working to make [finagle-http](https://github.com/twitter/finagle) available for aarch64 platform, which is dependent on netty version 4.1.51.Final and tcnative version 2.0.34.Final but when tcnative version 32/33/34 is used it is generating below [warning](https://drive.google.com/file/d/1KJbVLRYEr4KlyCyUHugvxzbNdXP_CZOK/view?usp=sharing):
```
Sep 30, 2020 9:50:01 AM io.netty.channel.ChannelInitializer exceptionCaught
WARNING: Failed to initialize a channel. Closing: [id: 0x70faddcf, L:/127.0.0.1:41677 - R:/127.0.0.1:53930]
java.lang.UnsupportedOperationException: JDK provider does not support NPN_AND_ALPN protocol
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:431)
	at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:249)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:465)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:571)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslConfigurations$.createServerContext(SslContext.scala:101)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerEngineFactory.apply(Netty4ServerEngineFactory.scala:27)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslChannelInitializer.$anonfun$initChannel$1(Netty4ServerSslChannelInitializer.scala:97)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslChannelInitializer.$anonfun$initChannel$1$adapted(Netty4ServerSslChannelInitializer.scala:94)
	at scala.Option.foreach(Option.scala:407)
	at com.twitter.finagle.netty4.ssl.server.Netty4ServerSslChannelInitializer.initChannel(Netty4ServerSslChannelInitializer.scala:94)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:181)
	at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:152)
	at com.twitter.finagle.netty4.channel.Netty4RawServerChannelInitializer.initChannel(Netty4RawServerChannelInitializer.scala:72)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
	at com.twitter.finagle.netty4.ListeningServerBuilder$$anon$1$$anon$2.initChannel(ListeningServerBuilder.scala:163)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)


```

And post finagle package is failing because I guess it is trying to use NPN_AND_ALPN protocol from java side (which doesn't seem supported in java) instead of using the same protocol from netty/tcnative.

Note: This error is not reproducible on x86_64 platform, so can say as aarch64 specific.

Also everything is working fine on aarch64 platform also if I will use tcnative version 2.0.31.Final instead of any recent version of tcnative.

**Comment by normanmaurer** [comment]
maybe this is related to https://github.com/netty/netty-tcnative/issues/571 ?

**Comment by odidev** [comment]
Hi,
Thanks @normanmaurer , I tried changes from referenced PR locally, but those doesn't seem fixing this issue.
Also, it was generating a jar with name having "aarch_64" in name.

**Comment by normanmaurer** [comment]
Closing this now... Please try with latest release
