### ISSUE TITLE
Building libraries on IBM z

### ISSUE THREAD

**Issue by jbuiibm** [netty/netty-tcnative#611]
Hi, we have an application provided by an external company that needs netty_tcnative to enable TLS.

The application is running in **OpenShift on IBM z** and fails when TLS is enabled due to missing tcnative library.

I found this document https://github.com/linux-on-ibm-z/docs/wiki/Building-netty-tcnative
and applied the manual steps so that our Docker image includes the needed .so library.
The setup is as follow:
- **Java version: "1.8.0_251", IBM J9VM, JRE 1.8.0 Linux s390x-64-bit**
- **Linux RHEL 8.2**
- **OpenSSL version 1.1.1g FIPS 21 Apr 2020**

The tests in the build are failing with the following error, could you help?
(also if I skip the tests, and generate the library I've got the same error when the application tries to load the library)

T E S T S

-------------------------------------------------------

Running io.netty.internal.tcnative.CertificateVerifierTest

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.075 sec <<< FAILURE! - in io.netty.internal.tcnative.CertificateVerifierTest

io.netty.internal.tcnative.CertificateVerifierTest  Time elapsed: 0.074 sec  <<< ERROR!

java.lang.UnsatisfiedLinkError: io/netty/internal/tcnative/Library.aprMajorVersion()I

        at io.netty.internal.tcnative.Library.initialize(Library.java:149)

        at io.netty.internal.tcnative.Library.initialize(Library.java:134)

        at io.netty.internal.tcnative.AbstractNativeTest.loadNativeLib(AbstractNativeTest.java:41)

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)

        at java.lang.reflect.Method.invoke(Method.java:508)

        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)

        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)

        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)

        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)

        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)

        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)

        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by jbuiibm** [comment]
Here is the docker part to build tcnative (I removed java and wget since they are already installed)

# 1. install needed modules
RUN yum install -y cmake perl gcc gcc-c++ openssl-devel apr-devel autoconf automake libtool make tar git python2 bzip2 zlib zlib-devel git xz diffutils  maven golang patch
RUN yum -y clean all 
RUN ln /usr/bin/python2 /usr/bin/python

# 2. install ninja 
RUN git clone https://github.com/ninja-build/ninja
WORKDIR /home/app/src/ninja
RUN git checkout v1.8.2
RUN ./configure.py --bootstrap

#PATH updated for Dockerfile
ENV PATH=/home/app/src/ninja:$PATH

# 3. download netty source code
WORKDIR /home/app/src
RUN git clone https://github.com/netty/netty-tcnative.git
WORKDIR /home/app/src/netty-tcnative
RUN git checkout netty-tcnative-parent-2.0.35.Final
 
# 3.1 build netty
RUN sed -i '59,59 s/chromium-stable/patch-s390x-Aug2019/g' pom.xml
RUN sed -i '100,100 s/boringssl.googlesource.com/github.com\/linux-on-ibm-z/g'  boringssl-static/pom.xml
RUN mvn install 
#-DskipTests=true

# 4 add to library path
ENV LD_LIBRARY_PATH=/home/app/src/netty-tcnative/openssl-dynamic/target/native-build/.libs/

# end building tcnative

**Comment by normanmaurer** [comment]
Sorry but this platform is not officially supported.
