### ISSUE TITLE
The tcnative works normally on TOMCAT, but JEUS and WEBLOGIC generate the following error:

### ISSUE THREAD

**Issue by izagood** [netty/netty-tcnative#627]
## My librarys
- netty-all-4.1.59.Final
- netty-tcnative-boringssl-static-2.0.36.Final

## Development environment
- windows 10
- eclipse
- tomcat

## Operating environment
- Tomcat => Fine
- JEUS , webtob => Errors occur
- WebLogic => Errors occur

```
java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:483)
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:192)
        at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:36)
        at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:191)
        at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:830)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:614)
```
```
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_hpux_unknown, netty_tcnative_unknown, netty_tcnative]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:104)
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:592)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:136)
        ... 16 more
```

## Question
1. Isn't the netty-tcnative-boringssl-static built in boringssl?
2. Does anyone know how to solve this problem?

Thank you in advance for your help.

**Comment by izagood** [comment]
JEUS - WebtoB service says it uses its own wbssl(I think it's a modified version of openssl.), can this be the cause?

**Comment by hyperxpro** [comment]
Which Operating System and Architecture is that?

**Comment by izagood** [comment]
> Which Operating System and Architecture is that?

I can't get the exact information because it's a server in the client company.

My manager sent me the error codes and informed me that the operating system is UNIX.

So I know the operating system is UNIX, but there is no information about architecture.

**Comment by normanmaurer** [comment]
We don't support hpux for netty-tcnative so this is expected.

**Comment by izagood** [comment]
> We don't support hpux for netty-tcnative so this is expected.

Thank you for your answer.
