### ISSUE TITLE
Link against to the libcrypt.so.2

### ISSUE THREAD

**Issue by floating-cat** [netty/netty-tcnative#703]
OS: Linux
Library: netty-tcnative-*-static

I just noticed that I am unable to run a Netty app in ArchLinux because Arch's glibc package has removed the libcrypt.so.1: https://bbs.archlinux.org/viewtopic.php?id=274160
So I need to install the `libxcrypt-compat` to run it.
From my checking, this is the same in the Fedora, and I think there would be more distro to remove it in the future.

To build a `libcrypt.so.1` from [besser82/libxcrypt](https://github.com/besser82/libxcrypt), the package need to not use the `--disable-obsolete-api` flag when building which is not used by some distros, and we need to install the `libxcrypt-compat` additionally.

Would it better if the `netty-tcnative-*-static` link against to the libcrypt.so.2 and recommend the users to install the `libxcrypt` package instead if they don't have the `libcrypt.so.2` installed?

Thanks.

Some reference links:
https://github.com/pypa/manylinux/issues/305#issuecomment-489332594
https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt

**Comment by arloor** [comment]
I ran into this problem on RHEL9 too.

```shell
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_641905760841177269486.so: libcrypt.so.1: cannot open shared object file: No such file or directory
        at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
        at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
        at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
        at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
        at java.lang.System.load(System.java:1953) ~[?:?]
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36) ~[forwardproxy-1.0-jar-with-dependencies.jar:?]
        ... 23 more
```
