### ISSUE TITLE
Accidental linkage to OpenSSL 3 on MacOS

### ISSUE THREAD

**Issue by chrisvest** [netty/netty-tcnative#719]
I've noticed that using the dynamically linked OpenSSL variant of tcnative on Intel MacOS, is trying to find `openssl@3`, while (as far as I understand) it's supposed to work with 1.1.1n.

Without `openssl@3` installed, I get the following error:

```
10:40:10.983 [main] DEBUG io.netty5.handler.ssl.OpenSsl - Failed to load netty-tcnative; OpenSslEngine will be unavailable, unless the application has already loaded the symbols by some other means. See https://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_osx_x86_64, netty_tcnative_x86_64, netty_tcnative]
	at io.netty5.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:115)
	at io.netty5.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:670)
	at io.netty5.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:143)
	at io.netty5.testsuite.transport.socket.SocketSslClientRenegotiateTest.openSslNotAvailable(SocketSslClientRenegotiateTest.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.api.condition.MethodBasedCondition.invokeConditionMethod(MethodBasedCondition.java:82)
	at org.junit.jupiter.api.condition.MethodBasedCondition.lambda$evaluateExecutionCondition$1(MethodBasedCondition.java:52)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.junit.jupiter.api.condition.MethodBasedCondition.evaluateExecutionCondition(MethodBasedCondition.java:52)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:64)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.lambda$evaluate$0(ConditionEvaluator.java:55)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
	at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:57)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:202)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$checkWhetherSkipped$3(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.checkWhetherSkipped(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:92)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
	Suppressed: java.lang.UnsatisfiedLinkError: /private/var/folders/qq/10lz4dss04l64_n8996ndyq80000gn/T/libnetty_tcnative_osx_x86_643284125934189316330.dylib: dlopen(/private/var/folders/qq/10lz4dss04l64_n8996ndyq80000gn/T/libnetty_tcnative_osx_x86_643284125934189316330.dylib, 0x0001): Library not loaded: /usr/local/opt/openssl@3/lib/libssl.3.dylib
  Referenced from: /private/var/folders/qq/10lz4dss04l64_n8996ndyq80000gn/T/libnetty_tcnative_osx_x86_643284125934189316330.dylib
  Reason: tried: '/usr/local/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file)
		at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
		at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
		at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
		at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
		at java.base/java.lang.Runtime.load0(Runtime.java:768)
		at java.base/java.lang.System.load(System.java:1834)
		at io.netty5.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
		at io.netty5.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:375)
		at io.netty5.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:204)
		at io.netty5.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
		... 70 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: /private/var/folders/qq/10lz4dss04l64_n8996ndyq80000gn/T/libnetty_tcnative_osx_x86_643284125934189316330.dylib: dlopen(/private/var/folders/qq/10lz4dss04l64_n8996ndyq80000gn/T/libnetty_tcnative_osx_x86_643284125934189316330.dylib, 0x0001): Library not loaded: /usr/local/opt/openssl@3/lib/libssl.3.dylib
  Referenced from: /private/var/folders/qq/10lz4dss04l64_n8996ndyq80000gn/T/libnetty_tcnative_osx_x86_643284125934189316330.dylib
  Reason: tried: '/usr/local/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/usr/lib/libssl.3.dylib' (no such file)
			at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
			at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
			at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
			at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
			at java.base/java.lang.Runtime.load0(Runtime.java:768)
			at java.base/java.lang.System.load(System.java:1834)
			at io.netty5.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.base/java.lang.reflect.Method.invoke(Method.java:566)
			at io.netty5.util.internal.NativeLibraryLoader.lambda$loadLibraryByHelper$0(NativeLibraryLoader.java:403)
			at java.base/java.security.AccessController.doPrivileged(Native Method)
			at io.netty5.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:397)
			at io.netty5.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:369)
			... 72 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path: [/Users/chris/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1870)
			at io.netty5.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty5.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:375)
			at io.netty5.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:147)
			... 71 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path: [/Users/chris/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1870)
				at io.netty5.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty5.util.internal.NativeLibraryLoader.lambda$loadLibraryByHelper$0(NativeLibraryLoader.java:403)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty5.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:397)
				at io.netty5.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:369)
				... 72 common frames omitted
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_x86_64
		at io.netty5.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:225)
		at io.netty5.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
		... 70 common frames omitted
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_64.jnilib
		at io.netty5.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:167)
		... 71 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: [/Users/chris/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1870)
			at io.netty5.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty5.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:375)
			at io.netty5.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:147)
			... 71 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: [/Users/chris/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1870)
				at io.netty5.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty5.util.internal.NativeLibraryLoader.lambda$loadLibraryByHelper$0(NativeLibraryLoader.java:403)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty5.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:397)
				at io.netty5.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:369)
				... 72 common frames omitted
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
		at io.netty5.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:225)
		at io.netty5.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
		... 70 common frames omitted
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.jnilib
		at io.netty5.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:167)
		... 71 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: [/Users/chris/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1870)
			at io.netty5.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty5.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:375)
			at io.netty5.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:147)
			... 71 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: [/Users/chris/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1870)
				at io.netty5.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty5.util.internal.NativeLibraryLoader.lambda$loadLibraryByHelper$0(NativeLibraryLoader.java:403)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty5.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:397)
				at io.netty5.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:369)
				... 72 common frames omitted
10:40:10.984 [main] DEBUG io.netty5.handler.ssl.OpenSsl - Initialize netty-tcnative using engine: 'default'
10:40:10.987 [main] DEBUG io.netty5.handler.ssl.OpenSsl - Failed to initialize netty-tcnative; OpenSslEngine will be unavailable. See https://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.UnsatisfiedLinkError: 'int io.netty.internal.tcnative.Library.aprMajorVersion()'
	at io.netty.internal.tcnative.Library.aprMajorVersion(Native Method)
	at io.netty.internal.tcnative.Library.initialize(Library.java:191)
	at io.netty5.handler.ssl.OpenSsl.initializeTcNative(OpenSsl.java:675)
	at io.netty5.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:160)
	at io.netty5.testsuite.transport.socket.SocketSslClientRenegotiateTest.openSslNotAvailable(SocketSslClientRenegotiateTest.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.api.condition.MethodBasedCondition.invokeConditionMethod(MethodBasedCondition.java:82)
	at org.junit.jupiter.api.condition.MethodBasedCondition.lambda$evaluateExecutionCondition$1(MethodBasedCondition.java:52)
	at java.base/java.util.Optional.map(Optional.java:265)
	at org.junit.jupiter.api.condition.MethodBasedCondition.evaluateExecutionCondition(MethodBasedCondition.java:52)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:64)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.lambda$evaluate$0(ConditionEvaluator.java:55)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
	at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:57)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:202)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$checkWhetherSkipped$3(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.checkWhetherSkipped(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:92)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by normanmaurer** [comment]
doh! Let me fix this

**Comment by normanmaurer** [comment]
Fixes by https://github.com/netty/netty-tcnative/pull/720
