### ISSUE TITLE
macOS12.4 M1 io.grpc:1.48.0 error : could not load a native library: netty_tcnative_osx_aarch_64

### ISSUE THREAD

**Issue by phial3** [netty/netty-tcnative#739]
```java
java.lang.UnsatisfiedLinkError: failed to load the required native library

	at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:596)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:830)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:611)
	at org.chainmaker.sdk.RpcServiceClient.initManagedChannel(RpcServiceClient.java:160)
	at org.chainmaker.sdk.RpcServiceClient.<init>(RpcServiceClient.java:83)
	at org.chainmaker.sdk.RpcServiceClient.newServiceClient(RpcServiceClient.java:91)
	at org.chainmaker.sdk.ChainManager.createChainClient(ChainManager.java:158)
	at org.chainmaker.sdk.ChainManager.createChainClient(ChainManager.java:143)
	at org.chainmaker.sdk.TestBase.init(TestBase.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_osx_aarch_64, netty_tcnative_aarch_64, netty_tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
	at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:169)
	at org.chainmaker.sdk.RpcServiceClient.getSslContextBuilder(RpcServiceClient.java:204)
	at org.chainmaker.sdk.RpcServiceClient.initManagedChannel(RpcServiceClient.java:147)
	... 33 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_osx_aarch_64
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 38 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_osx_aarch_64.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:181)
		... 39 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_aarch_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
			at java.lang.Runtime.loadLibrary0(Runtime.java:872)
			at java.lang.System.loadLibrary(System.java:1124)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 39 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_aarch_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
				at java.lang.Runtime.loadLibrary0(Runtime.java:872)
				at java.lang.System.loadLibrary(System.java:1124)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 40 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_aarch_64
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 38 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_aarch_64.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:181)
		... 39 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_aarch_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
			at java.lang.Runtime.loadLibrary0(Runtime.java:872)
			at java.lang.System.loadLibrary(System.java:1124)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 39 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_aarch_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
				at java.lang.Runtime.loadLibrary0(Runtime.java:872)
				at java.lang.System.loadLibrary(System.java:1124)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 40 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 38 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:181)
		... 39 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
			at java.lang.Runtime.loadLibrary0(Runtime.java:872)
			at java.lang.System.loadLibrary(System.java:1124)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 39 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
				at java.lang.Runtime.loadLibrary0(Runtime.java:872)
				at java.lang.System.loadLibrary(System.java:1124)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 40 more
```
<img width="597" alt="image" src="https://user-images.githubusercontent.com/27754514/182009741-973df778-c163-4350-92eb-41050e449c9d.png">

**Comment by phial3** [comment]
Can help me?

**Comment by yeikel** [comment]
We are seeing a similar error  

io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.39.Final

Could you please create a build targeting this platform?

**Comment by tholu** [comment]
Similar problem: `Could not find artifact io.netty:netty-tcnative:jar:osx-aarch_64:2.0.58.Final`

**Comment by normanmaurer** [comment]
you need to depend on netty-tcnative-boringssl-static
