### ISSUE TITLE
where can I find the compatibility b/w netty-tcnative and other netty components (netty-transport, netty-handlers, etc..)

### ISSUE THREAD

**Issue by xianggao001** [netty/netty-tcnative#755]
Hi, I met an issue: 
```
Caused by: java.lang.Exception: Not supported using BoringSSL
	at io.netty.internal.tcnative.SSLContext.setCertRequestedCallback(Native Method)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext.newSessionContext(ReferenceCountedOpenSslClientContext.java:115)

```

and by searching I know some netty-all version is required (https://github.com/jchambers/pushy/issues/733). However, I can not find an official doc stating the compatibility b/w netty-tcnative and other netty components. Is there such a guidance?  Thanks!

**Comment by normanmaurer** [comment]
@xianggao001 we release a netty-bom which has the right version in it.
