### ISSUE TITLE
Issue encountered in tcnative 2.0.54.Final java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSLPrivateKeyMethod

### ISSUE THREAD

**Issue by sleepyGeek** [netty/netty-tcnative#765]
Hi, as part of addressing vulnerability issue in the previous version (2.0.46.Final), we are now upgrading to 2.0.54.Final..
We upgrade netty libariries to 4.1.86.Final, then tcnative to 2.0.54.Final...
After this, we encountered the following issues,..

`2821661: Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSLPrivateKeyMethod
2821754-        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
2821818-        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2821877-        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
2821944-        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2822003-        ... 10 more
`

any thoughts what could have changed and cause this issue?
Thanks...

**Comment by normanmaurer** [comment]
You most likely have multiple version on the class path

**Comment by sleepyGeek** [comment]
Thank  you for response @normanmaurer , but as per checking the logs, I only see 1 version of tcnative, but still issue persist..

```
436815-   /ugbu-server/service/lib/netty-codec-socks-4.1.86.Final.jar
436878-   /ugbu-server/service/lib/netty-common-4.1.86.Final.jar
436936-   /ugbu-server/service/lib/netty-handler-4.1.86.Final.jar
436995-   /ugbu-server/service/lib/netty-handler-proxy-4.1.86.Final.jar
437060-   /ugbu-server/service/lib/netty-resolver-4.1.86.Final.jar
437120:   /ugbu-server/service/lib/netty-tcnative-2.0.54.Final-linux-x86_64.jar
437193-   /ugbu-server/service/lib/netty-transport-4.1.86.Final.jar
437254-   /ugbu-server/service/lib/netty-transport-classes-epoll-4.1.86.Final.jar
437329-   /ugbu-server/service/lib/netty-transport-native-epoll-4.1.86.Final.jar
437403-   /ugbu-server/service/lib/netty-transport-native-unix-common-4.1.86.Final.jar
437483-   /ugbu-server/service/lib/ojdbc8-19.12.0.0.0.jar
```


```
538607:secrets-privileged-server-69f65796f8-plvqp 10.193.61.15 Secrets-Priviliged ERROR 1 1  unknown  com.oracle.ugbu.core.chassis.ChassisRunner 155851 ThreadName: main TraceID: unknown  CorelationID: cd7bbc5e-0bbf-414a-8508-7d1a48268199  Message: Uncaught exception from chassis service, with app's osExitCode=0 java.lang.NoClassDefFoundError: io/netty/internal/tcnative/SSLPrivateKeyMethod
538992-         at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:474)
539075-         at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606)
539153-         at com.oracle.ugbu.mt.shared.util.ssl.AbstractSSLContextSupplier.get(AbstractSSLContextSupplier.java:66)
539260-         at com.oracle.ugbu.mt.shared.util.ssl.AbstractSSLContextSupplier.get(AbstractSSLContextSupplier.java:20)
539367-         at com.oracle.ugbu.mt.shared.util.ssl.SslContextReloader.load(SslContextReloader.java:34)
539459-         at com.oracle.ugbu.mt.shared.util.ssl.SslContextReloader.<init>(SslContextReloader.java:28)
539553-         at com.oracle.ugbu.secrets.server.SecretPrivilegedServer.run(SecretPrivilegedServer.java:191)
539649-         at com.oracle.ugbu.core.chassis.ChassisRunner.run(ChassisRunner.java:285)
539725-         at com.oracle.ugbu.core.chassis.ChassisRunner.run(ChassisRunner.java:276)
539801-         at com.oracle.ugbu.core.chassis.ChassisRunner.main(ChassisRunner.java:200)
539878: Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSLPrivateKeyMethod
539971-         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
540035-         at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
540094-         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
540161-         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
540220-         ... 10 more

```

**Comment by normanmaurer** [comment]
`netty-tcnative-classes` is missing.

**Comment by sleepyGeek** [comment]
hi @normanmaurer I added the netty-tcnative-classes in the dependency and that worked.. 
thank you very much....
