### ISSUE TITLE
Failed to loadLibrary on linux X86_64 with netty-tcnative version >= 2.0.57

### ISSUE THREAD

**Issue by wonderedge** [netty/netty-tcnative#806]
Hi, I'm using boringssl-static with netty, it thrown an exception as below after I upgrade netty-tcnative version to 2.0.57:
``` shell
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/conf/etc/libnetty_tcnative_linux_x86_64.so: /opt/conf/etc/libnetty_tcnative_linux_x86_64.so: undefined symbol: _Unwind_GetRegionStart
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
        at java.lang.Runtime.loadLibrary0(Runtime.java:843)
        at java.lang.System.loadLibrary(System.java:1136)
```
but everything was fine with 2.0.56, what changes between these versions may cause this failure and what should I do to fix this?

**Comment by normanmaurer** [comment]
Please upgrade to latest version ...
