### ISSUE TITLE
ubuntu linux support for openssl 3.x

### ISSUE THREAD

**Issue by mason124124** [netty/netty-tcnative#876]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/huwen/dev/tools/gradle_user_home/native/libnetty_tcnative_linux_x86_64.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)

looks like the libnetty_tcnative_linux_x86_64.so requires openssl 1.0.0. Is this PR fix the issue? 
https://github.com/netty/netty-tcnative/commit/c9b4b6ab62cdbfb4aab6ab3efb8dd7cf73f353ad

When will 2.0.66.FINAL be released?

**Comment by gapropp123** [comment]
Hi @mason124124, version 2.0.66.Final has been released. Are you still experiencing that issue? I'm currently on this version and still facing it

**Comment by vinsonxing** [comment]
Same issue here....

**Comment by alexanderankin** [comment]
When i download the latest release and do the following check, i get:

```console
$ wget https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.72.Final/netty-tcnative-2.0.72.Final-linux-x86_64.jar
$ unzip -jo netty-tcnative-2.0.72.Final-linux-x86_64.jar  META-INF/native/libnetty_tcnative_linux_x86_64.so
$ ldd libnetty_tcnative_linux_x86_64.so | grep libssl
	libssl.so.1.0.0 => not found
```

however, when i compile it from source with ./mvnw package (after having apt installed:

https://github.com/netty/netty-tcnative/blob/53102a197cb92c554fda59f7893fddbd65b6c1f7/.github/workflows/codeql-analysis.yml#L79-L80

i can find these files:

```console
$ find . -name '*.so'
./openssl-static/target/openssl/lib/ossl-modules/legacy.so
./openssl-static/target/openssl-source/providers/legacy.so
./openssl-static/target/openssl-source/test/p_test.so
./openssl-static/target/openssl-source/test/p_minimal.so
./openssl-dynamic/target/native-jar-work/META-INF/native/libnetty_tcnative_linux_x86_64.so
./openssl-dynamic/target/native-build/target/lib/libnetty_tcnative.so
./openssl-dynamic/target/native-build/target/lib/libnetty_tcnative-@VERSION@.so
./openssl-dynamic/target/native-build/.libs/libnetty_tcnative.so
./openssl-dynamic/target/native-build/.libs/libnetty_tcnative-@VERSION@.so
./openssl-dynamic/target/test-classes/META-INF/native/linux64/libnetty_tcnative.so
./openssl-dynamic/target/native-lib-only/META-INF/native/linux64/libnetty_tcnative.so
$ for i in $(find . -name '*.so'); do echo $i $(ldd $i | grep ssl); done
./openssl-static/target/openssl/lib/ossl-modules/legacy.so
./openssl-static/target/openssl-source/providers/legacy.so
./openssl-static/target/openssl-source/test/p_test.so
./openssl-static/target/openssl-source/test/p_minimal.so
./openssl-dynamic/target/native-jar-work/META-INF/native/libnetty_tcnative_linux_x86_64.so libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x0000717842351000)
./openssl-dynamic/target/native-build/target/lib/libnetty_tcnative.so libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007ee16d3d9000)
./openssl-dynamic/target/native-build/target/lib/libnetty_tcnative-@VERSION@.so libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007416c09a6000)
./openssl-dynamic/target/native-build/.libs/libnetty_tcnative.so libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007dc672f90000)
./openssl-dynamic/target/native-build/.libs/libnetty_tcnative-@VERSION@.so libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007cff67a6b000)
./openssl-dynamic/target/test-classes/META-INF/native/linux64/libnetty_tcnative.so libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x0000750477550000)
./openssl-dynamic/target/native-lib-only/META-INF/native/linux64/libnetty_tcnative.so libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x000075d2daea3000)
```

so what's going on?

**Comment by alexanderankin** [comment]
err, looks like boringssl static variant does work for my test case, but im not convinced upgrading openssl versions is not still pertinent in case that variant must be used for whatever case...

**Comment by normanmaurer** [comment]
This was done
